version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0
    ports:
      -   "9000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:kali@localhost:5432/question_quiz
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=localhost
      - POSTGRES_DB=question_quiz

volumes:
  postgres_data:
